# Generated by Django 5.1.5 on 2025-02-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_short_description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('In progress', 'In progress'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], max_length=500)),
                ('case_type', models.CharField(choices=[('Potholes', 'Potholes'), ('Street lighting', 'Street lighting'), ('Graffiti', 'Graffiti'), ('Anti-Social behavior', 'Anti-Social behavior'), ('Other', 'Other')], max_length=1000)),
                ('case_image', models.ImageField(blank=True, null=True, upload_to='case_images/')),
                ('staff_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('user_raised', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cases_raised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
