# Generated by Django 5.1.5 on 2025-02-01 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0003_alter_case_staff_assigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_long_description',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='staff_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_cases_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='user_raised',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cases_raised0', to=settings.AUTH_USER_MODEL),
        ),
    ]
