# Generated by Django 5.1.5 on 2025-02-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0005_alter_case_case_long_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_long_description',
            new_name='comments',
        ),
    ]
