# Generated by Django 5.1.5 on 2025-02-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0006_rename_case_long_description_case_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='user_raised',
        ),
        migrations.AddField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='telephone',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/case_images/'),
        ),
    ]
