# Generated by Django 5.1.5 on 2025-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0007_remove_case_user_raised_case_email_case_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('In progress', 'In progress'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Not assigned', max_length=500),
        ),
    ]
