# Generated by Django 5.1.5 on 2025-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0008_alter_case_name_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='telephone',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
