# Generated by Django 5.1.5 on 2025-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0009_alter_case_email_alter_case_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
