# Generated by Django 5.1.5 on 2025-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0010_alter_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_short_description',
        ),
        migrations.AddField(
            model_name='case',
            name='impact_description',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='issue_description',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='propsed_action',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='telephone',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
