# Generated by Django 5.1.5 on 2025-03-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilComplaintsBackend', '0011_remove_case_case_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='propsed_action',
            new_name='proposed_action',
        ),
        migrations.AlterField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
